### ISSUE TITLE
More doesn't clean up unused css

### ISSUE THREAD

**Issue by Meai1** [kevin-montrose/More#6]
Steps to reproduce:
1. create test.more
2. Add

```
img { width: 10px; @(.avatar); }
p { font-color: grey; }
@media tv {
  p { font-color: black; }
  .avatar { border-width: 1px; @(p); }
  .wrapper { height:10px; @(img); }
}
```
1. compile test.more
2. Now replace everything in test.more with

```
@reset{
  h1 { margin: 0; }
}
.class h1 { color: blue; }
```
1. compile test.more
2. Weirdly the media rule is still there, it hasn't been cleaned up.

**Comment by kevin-montrose** [comment]
Fairly certain this was fixed in [this commit](https://github.com/kevin-montrose/More/commit/a03bf7ed85a560943f21cf3a200e5bc955df0ca2).

[Updated download](https://github.com/downloads/kevin-montrose/More/More%20v1.1c.zip) should contain that fix.

Note that there was _another_ bug with overwriting files also fixed in that download, you should have to use the `/f` flag to overwrite files that already exist.

**Comment by Meai1** [comment]
thanks! the /f flag worked, pretty important. Without it on Linux it just keeps creating new files like test(1).css test(2).css
